### ISSUE TITLE
Why set up this project?

### ISSUE THREAD

**Issue by coderjiav** [JCotton1123/php-jdbc-bridge#4]
Hi guys,
    I am now using php to connect SAP HANA and found that there is no official driver for PHP but for JAVA it has. So it seems your project is suit for me.  But I still search for any other way except this. So I want to know why you set up this project? Do you also have the same problem?

Thanks a lot in advance.

**Comment by JCotton1123** [comment]
@coderjiav yes, I ran into the same problem. I had to integrate a large PHP application with a database that only offered a JDBC driver. This was the best workaround I could find.
