### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ghost** [JCotton1123/php-jdbc-bridge#6]
Hi,

first of all, thanks for taking the time to maintain this project.

I am currently considering using this in one of my projects, however I need to know if this is released under a compatible license.

As this was forked from an LGPL 2.0 project, am I correct in assuming that this is also LGPL 2.0? Could you please add a LICENSE file to clarify?

Thanks!

**Comment by JCotton1123** [comment]
Done :)

**Comment by ghost** [comment]
Thanks a lot.

In the mean time I stumbled upon some GPLv2 license headers, whereas the original project homepage says it should be LGPL.

Do you have any more information about the licensing history of the original software?

Thanks in advance!

**Comment by JCotton1123** [comment]
@XitasoChris I hadn't noticed that myself but I see that now. Unfortunately I don't have any additional information on the licensing, and haven't been in contact with the original author.

**Comment by JCotton1123** [comment]
@XitasoChris from some quick research it appears that GPLv2 and LGPLv2 are compatible? Also, it looks like the library includes source that was not authored by the author of PJBS so that may be why some of the headers are different.

**Comment by ghost** [comment]
@JCotton1123 Thanks for the info. AFAIK, LGPL code can be incorporated into GPL projects, but GPL cannot be "downgraded" to LGPL as LGPL is more permissive than GPL. So I'm wondering whether there might be some licensing issues further up the chain (i.e. already in PJBS) which would effectively make the entire software GPL which would prevent me from using it in my project.

I will talk to my legal guys, see what they think. Thanks again for your help!
