### ISSUE TITLE
error: could not load JDBC driver

### ISSUE THREAD

**Issue by krasnikovdev** [JCotton1123/php-jdbc-bridge#9]
Hi. 
I try run your app

> java -cp 'lib/pjbridge.jar:lib/commons-daemon-1.2.2.jar:lib/dharma.jar' Server dharma.jdbc.DharmaDriver 4444

but i have this error
> error: could not load JDBC driver

And this file lib/dharma.jar dosn't exists.

How can I load JDBC driver?
Thanks.

**Comment by JCotton1123** [comment]
Hi, the above is just an example. You need to substitute `dharma.jar` with your JDBC driver. Additionally the entry point, `dharma.jdbc.DharmaDriver`, will need to be updated to match your driver.

**Comment by krasnikovdev** [comment]
Can i use many drivers in one instanse for example mysql, oracle and postgre?

**Comment by JCotton1123** [comment]
No but you can start multiple instances of the service on different ports where each one is using a different driver, and connect to them from a single PHP application.

**Comment by krasnikovdev** [comment]
Thanks.

**Comment by viru2001** [comment]
> Hi, the above is just an example. You need to substitute `dharma.jar` with your JDBC driver. Additionally the entry point, `dharma.jdbc.DharmaDriver`, will need to be updated to match your driver.

how to get entry point ?

**Comment by viru2001** [comment]
> Hi, the above is just an example. You need to substitute `dharma.jar` with your JDBC driver. Additionally the entry point, `dharma.jdbc.DharmaDriver`, will need to be updated to match your driver.

how to get entry point ?

**Comment by JCotton1123** [comment]
@viru2001 you would have to find this in the documentation for your driver.

**Comment by viru2001** [comment]
> @viru2001 you would have to find this in the documentation for your driver.

thanks .
